Fixed subtle BASH bug
From shellcheck:
Note that A && B || C is not if-then-else. C may run when A is true. [SC2015]

diff --git a/src/palantír/palantir b/src/palantír/palantir
--- a/src/palantír/palantir
+++ b/src/palantír/palantir
@@ -64,10 +64,10 @@ list_issues_change_since() {
     dir=${src_dir}/${repo_name}
     if [ -d "${dir}" ]; then
       (
-        cd "${dir}" &&
-          git pull &> /dev/null || {
-            echo "Couldn't pull $(red "${repo_name}"), using offline"
-          }
+        cd "${dir}" || exit 1
+        git pull &> /dev/null || {
+          echo "Couldn't pull $(red "${repo_name}"), using offline"
+        }
       )
     else
       (
